<?php
return array(
    array(
        'id'              => 'logodesign',
        'title'           => 'Logo Design Prices',
        'title_portfolio' => 'Logo Design Portfolio',
        'description'     => 'Logo Design - Special Combination Packages',
        'num_portfolio'   => 0,
        'packages'        => array(
            array(
                'id'                   => 'budget_package',
                'name'                 => 'Budget Pkg',
                'discount'             => true,
                'price'                => '99',
                'original_price'       => '125',
                'initial_concepts'     => 4,
                'team_members'         => 2,
                'turn_around'          => '1-3',
                'css_highlight_colour' => 'orange',
                'css_heading_colour'   => '',
            ),
            array(
                'id'                       => 'basic_package',
                'name'                     => 'Basic Pkge',
                'price'                    => '199',
                'initial_concepts'         => 6,
                'team_members'             => 3,
                'custom_stationery_design' => 1,
                'css_highlight_colour'     => 'blue',
                'css_heading_colour'       => 'yellow',
            ),
            array(
                'id'                       => 'advance_package',
                'name'                     => 'Advance Pkge',
                'price'                    => '399',
                'initial_concepts'         => 8,
                'team_members'             => 4,
                'custom_stationery_design' => 1,
                'css_highlight_colour'     => 'darkblue',
                'css_heading_colour'       => 'yellow',
            ),
            array(
                'id'                       => 'pro_package',
                'name'                     => 'Pro Pkge',
                'price'                    => '425',
                'initial_concepts'         => 10,
                'team_members'             => 5,
                'custom_stationery_design' => 0,
                'turn_around'              => '1-3',
                'css_highlight_colour'     => 'darkgreen',
                'css_heading_colour'       => '',
            ),
            array(
                'id'                       => 'pro_advance_package',
                'name'                     => 'Adv-Pro Pkge',
                'price'                    => '899',
                'initial_concepts'         => 12,
                'team_members'             => 6,
                'custom_stationery_design' => 1,
                'website_design'           => 5,
                'turn_around'              => '1-3',
                'css_highlight_colour'     => 'blueshade',
                'css_heading_colour'       => 'bluedarkshade',
            ),
            array(
                'id'                       => 'pro_plus_package',
                'name'                     => 'Pro Plus Pkge',
                'price'                    => '1325',
                'initial_concepts'         => 'Unlimited',
                'team_members'             => 6,
                'custom_stationery_design' => 2,
                'website_design'           => 10,
                'turn_around'              => '1-3',
                'css_highlight_colour'     => 'darkred',
                'css_heading_colour'       => 'yellow',
            ),
        ),
    ),
    array(
        'id'              => 'webdesign',
        'title'           => 'Web Design Prices',
        'title_portfolio' => 'Web Design Portfolio',
        'description'     => 'Web Design - Special Combination Packages',
        'num_portfolio'   => 40,
        'packages'        => array(
            array(
                'id'                   => 'budget_package',
                'name'                 => 'Budget W-Pkg',
                'price'                => '249',
                'website_design'       => 2,
                'team_members'         => 1,
                'initial_concepts'     => 1,
                'turn_around'          => '1-3',
                'css_highlight_colour' => 'orange',
                'css_heading_colour'   => '',
            ),
            array(
                'id'                   => 'basic_package',
                'name'                 => 'Static W-Pkg',
                'price'                => '425',
                'website_design'       => 5,
                'team_members'         => 2,
                'initial_concepts'     => 1,
                'turn_around'          => '1-3',
                'css_highlight_colour' => 'blue',
                'css_heading_colour'   => 'yellow',
            ),
            array(
                'id'                   => 'advance_package',
                'name'                 => 'Custom W-Pkg',
                'price'                => '849',
                'website_design'       => 10,
                'team_members'         => 3,
                'initial_concepts'     => 1,
                'turn_around'          => '1-3',
                'css_highlight_colour' => 'darkblue',
                'css_heading_colour'   => 'yellow',
            ),
            array(
                'id'             => 'pro_package',
                'name'           => 'Dynamic W-Pkg',
                'price'          => '1325',
                'website_design' => 20,
                'member_area'    => true,
                'cms'            => true,
                'php'            => true,

                'css_highlight_colour' => 'darkgreen',
                'css_heading_colour'   => '',
            ),
            array(
                'id'             => 'pro_plus_package',
                'name'           => 'Dyn-Pro Pkge',
                'price'          => '1825',
                'website_design' => 25,
                'member_area'    => true,
                'cms'            => true,
                'php'            => true,

                'css_highlight_colour' => 'darkred',
                'css_heading_colour'   => 'yellow',
            ),
        ),
    ),
    array(
        'id'              => 'stationery',
        'title'           => 'Stationery Prices',
        'title_portfolio' => 'Stationery Portfolio',
        'description'     => 'Stationery Design - Special Combination Packages',
        'num_portfolio'   => 16,
        'packages'        => array(
            array(
                'id'                    => 'budget_package',
                'name'                  => 'Card Design',
                'price'                 => '49',
                'team_members'          => 2,
                'initial_concepts'      => 2,
                'turn_around'           => '1-3',
                'custom_business_cards' => 2,
                'css_highlight_colour'  => 'orange',
                'css_heading_colour'    => '',
            ),
            array(
                'id'                       => 'basic_package',
                'name'                     => 'Stationery Pkg',
                'price'                    => '99',
                'team_members'             => 1,
                'initial_concepts'         => 1,
                'turn_around'              => '1-3',
                'custom_stationery_design' => 1,
                'css_highlight_colour'     => 'blue',
                'css_heading_colour'       => 'yellow',
            ),
            array(
                'id'                       => 'advance_package',
                'name'                     => 'Branding Pkge',
                'price'                    => '175',
                'team_members'             => 2,
                'initial_concepts'         => 1,
                'turn_around'              => '1-3',
                'custom_stationery_design' => 2,
                'css_highlight_colour'     => 'darkblue',
                'css_heading_colour'       => 'yellow',
            ),
        ),
    ),
    array(
        'id'              => 'brochure',
        'title'           => 'Brochure Prices',
        'title_portfolio' => 'Brochure Portfolio',
        'description'     => 'Brochure Design - Special Combination Packages',
        'num_portfolio'   => 12,
        'packages'        => array(
            array(
                'id'                   => 'budget_package',
                'name'                 => 'Tri-Fold Pkg',
                'price'                => '249',
                'team_members'         => 1,
                'initial_concepts'     => 1,
                'turn_around'          => '1-3',
                'custom_brochure'      => 1,
                'css_highlight_colour' => 'orange',
                'css_heading_colour'   => '',
            ),
            array(
                'id'                   => 'basic_package',
                'name'                 => 'Bifold Pkg',
                'price'                => '349',
                'team_members'         => 2,
                'initial_concepts'     => 1,
                'turn_around'          => '1-3',
                'custom_brochure'      => 4,
                'css_highlight_colour' => 'blue',
                'css_heading_colour'   => 'yellow',
            ),
            array(
                'id'                       => 'advance_package',
                'name'                     => 'Bifold-Pro Pkg',
                'price'                    => '675',
                'team_members'             => 3,
                'initial_concepts'         => 1,
                'turn_around'              => '1-3',
                'custom_brochure'           => 8,
                'css_highlight_colour'     => 'darkblue',
                'css_heading_colour'       => 'yellow',
            ),
        ),
    ),
    array(
        'id'              => 'illustration',
        'title'           => 'Illustration Price',
        'title_portfolio' => 'Illustration Portfolio',
        'description'     => 'Illustration design - Special Combination Packages',
        'num_portfolio'   => 18,
        'packages'        => array(
            array(
                'id'                   => 'budget_package',
                'name'                 => 'Basic Ilt-Pkg',
                'price'                => '149',
                'sketch'               => 1,
                'team_members'         => 1,
                'initial_concepts'     => 1,
                'turn_around'          => '1-3',
                'custom_illustration'  => 1,
                'css_highlight_colour' => 'orange',
                'css_heading_colour'   => '',
            ),
            array(
                'id'                   => 'basic_package',
                'name'                 => 'Adv-Ilt Pkg',
                'price'                => '249',
                'sketch'               => 2,
                'team_members'         => 2,
                'initial_concepts'     => 1,
                'turn_around'          => '1-3',
                'custom_illustration'  => 2,
                'css_highlight_colour' => 'blue',
                'css_heading_colour'   => 'yellow',
            ),
            array(
                'id'                   => 'advance_package',
                'name'                 => 'Custom-ilt Pkg',
                'price'                => '375',
                'sketch'               => 3,
                'team_members'         => 3,
                'initial_concepts'     => 1,
                'turn_around'          => '1-3',
                'custom_illustration'  => 3,
                'css_highlight_colour' => 'darkblue',
                'css_heading_colour'   => 'yellow',
            ),
        ),
    ),
);
